version: "3.8"

services:
  api:
    build:
      context: .
      args:
        VERSION: dev
    ports:
      - "3000:80"
    environment:
      BASE_URI: localhost:3000
      SCHEME_HTTPS: "false"
      POSTGRES_HOST: postgres
      POSTGRES_USER: helpwave
      POSTGRES_PASSWORD: helpwave
      POSTGRES_DB: helpwave
    depends_on:
      - migrate

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: helpwave
      POSTGRES_PASSWORD: helpwave
      POSTGRES_DB: helpwave
    volumes:
      - "postgres-helpwave:/var/lib/postgresql/data"

  migrate:
    image: migrate/migrate
    volumes:
      - "./db/migrations:/migrations"
    command: [
        "-path",
        "/migrations",
        "-database",
        "postgres://helpwave:helpwave@postgres:5432/helpwave?sslmode=disable",
        "up",
    ]
    depends_on:
      - postgres

  mocks:
      image: postgres
      command: /bin/sh -c 'echo "SELECT COUNT(id) FROM emergency_rooms;" | psql --csv -q | grep 0 && psql -f mocks.sql'
      environment:
          PGHOST: postgres
          PGUSER: helpwave
          PGPASSWORD: helpwave
          PGDATABASE: helpwave
      volumes:
          - "./db/mocks.sql:/mocks.sql:ro"
      depends_on:
          - migrate

volumes:
  postgres-helpwave:
