version: "3.8"

services:
  api:
    build: .
    restart: always
    ports:
      - "80:80"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: helpwave
      POSTGRES_PASSWORD: helpwave
      POSTGRES_DB: helpwave
    healthcheck:
      test: curl --fail http://localhost/v1/healthz || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: helpwave
      POSTGRES_PASSWORD: helpwave
      POSTGRES_DB: helpwave
    volumes:
      - postgres-helpwave:/var/lib/postgresql/data

volumes:
  postgres-helpwave:
