version: "3.8"

services:
  api:
    build:
      context: .
      args:
        VERSION: dev
    ports:
      - "3000:80"
    environment:
      SCHEME_HTTPS: "false"
      BASE_URI: localhost:3000
      POSTGRES_HOST: postgres
      POSTGRES_USER: helpwave
      POSTGRES_PASSWORD: helpwave
      POSTGRES_DB: helpwave
    depends_on:
      - migrate

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: helpwave
      POSTGRES_PASSWORD: helpwave
      POSTGRES_DB: helpwave
    volumes:
      - "postgres-helpwave:/var/lib/postgresql/data"

  migrate:
    image: migrate/migrate
    volumes:
      - "./db/migrations:/migrations"
    command: [
        "-path",
        "/migrations",
        "-database",
        "postgres://helpwave:helpwave@postgres:5432/helpwave?sslmode=disable",
        "up",
    ]
    depends_on:
      - postgres

volumes:
  postgres-helpwave:
