-- Data Generated using mockaroo

-- Rooms
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Mock Hospital One', point(34.238555, 117.196805), 'Mock Street 5, 123456 Cityname', true);

INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Ephippiorhynchus mycteria', point(51.2092169, 35.2291386), '25304 Lakeland Circle', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Deroptyus accipitrinus', point(-7.3260543, 108.3655011), '39 Stephen Pass', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Ploceus intermedius', point(-6.8432007, 107.612654), '70569 Mcguire Avenue', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('unavailable', point(51.8909212, 21.0863266), '8507 Bonner Crossing', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Neotoma sp.', point(55.7133263, 37.8049211), '2679 Mayer Drive', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Caiman crocodilus', point(-6.6858425, -36.6602483), '7649 Waxwing Hill', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Axis axis', point(34.1301599, -117.2690813), '90280 South Road', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Anas bahamensis', point(45.9559485, 14.3016556), '31 Dorton Drive', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Lophoaetus occipitalis', point(31.2660017, 70.8743691), '5 Buena Vista Road', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Salvadora hexalepis', point(33.765469, 113.994752), '40 Lakeland Street', false);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Myiarchus tuberculifer', point(48.2211075, 26.2712988), '40 Luster Drive', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Haliaeetus leucocephalus', point(22.454973, 89.9437755), '7169 Esch Park', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Colaptes campestroides', point(43.7633364, 26.6950125), '3 Talmadge Street', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Taurotagus oryx', point(57.42746, 15.08533), '76 Fairview Crossing', false);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Semnopithecus entellus', point(48.9763601, 17.4746428), '97228 Hoffman Place', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Equus hemionus', point(24.094765, 116.00509), '41 Reinke Circle', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Sciurus vulgaris', point(-7.3554007, -35.2258365), '8 Sherman Parkway', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Phascogale calura', point(56.6845023, 16.3327786), '21 Browning Circle', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Nyctereutes procyonoides', point(54.0077659, 16.0063249), '0250 Vermont Pass', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Ceratotherium simum', point(40.8875343, 19.5880506), '40 Carpenter Court', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Priodontes maximus', point(-1.5697615, 110.5215459), '94 Walton Parkway', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Limnocorax flavirostra', point(41.1279946, -7.9859629), '57026 Meadow Ridge Crossing', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Hystrix cristata', point(29.407391, 106.543713), '52420 Kingsford Hill', false);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Castor fiber', point(38.067932, 111.797083), '75907 Butterfield Court', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Manouria emys', point(34.0665041, 47.9762632), '5775 Meadow Ridge Trail', false);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Eutamias minimus', point(-18.4097245, -49.2162908), '05 Spaight Pass', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Cynictis penicillata', point(32.890479, 115.814504), '9766 Birchwood Crossing', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Amazona sp.', point(29.169486, 89.220664), '38 Parkside Pass', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Choloepus hoffmani', point(50.1383356, 14.6705894), '1746 Buhler Junction', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Butorides striatus', point(15.767975, 101.010223), '1470 Mariners Cove Hill', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Zalophus californicus', point(52.083111, 20.3863042), '94293 Vernon Drive', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Ardea golieth', point(29.8572576, 59.9739243), '58 Miller Place', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Felis silvestris lybica', point(48.5264861, 25.5701022), '34 Melby Place', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Cracticus nigroagularis', point(56.227929, 35.6372213), '0632 Almo Point', false);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Leptoptilos crumeniferus', point(-9.8232056, -77.6493992), '23106 Grim Way', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Tachybaptus ruficollis', point(52.3048562, 15.4108777), '70 Alpine Trail', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Columba livia', point(41.1588991, -8.0638522), '00679 Esker Parkway', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Milvus migrans', point(49.7938443, 36.0269813), '34 Bobwhite Place', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Eudromia elegans', point(68.7986342, 16.5414503), '02 Park Meadow Crossing', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Stercorarius longicausus', point(10.142762, -85.454983), '675 Dunning Terrace', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Dusicyon thous', point(43.6297603, 0.5815411), '67026 Texas Lane', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Trichosurus vulpecula', point(12.6679167, 123.9881642), '95 Thompson Avenue', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Ammospermophilus nelsoni', point(58.5642523, 12.0657604), '7 Spenser Alley', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Alopochen aegyptiacus', point(29.0654415, 120.2512222), '7 Marcy Alley', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Charadrius tricollaris', point(39.9831117, -75.1150466), '0 1st Parkway', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Arctogalidia trivirgata', point(43.6953508, 7.2559678), '748 Sutherland Place', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Zosterops pallidus', point(15.3098074, 120.8551691), '729 Brown Plaza', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Felis yagouaroundi', point(-2.0669719, 101.39186), '5112 Green Pass', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Bucephala clangula', point(44.3338201, 85.6264576), '19405 Londonderry Point', false);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Pseudalopex gymnocercus', point(39.553172, 98.981746), '818 Hazelcrest Avenue', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Phasianus colchicus', point(6.9433577, -70.7168469), '5675 Heffernan Terrace', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Morelia spilotes variegata', point(9.7986027, 38.4271461), '6 Lakewood Gardens Junction', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Ovibos moschatus', point(-7.5888579, 108.2674092), '8 Mariners Cove Street', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Buteo galapagoensis', point(52.2183563, 35.2154784), '13050 Westerfield Center', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Canis mesomelas', point(28.5091355, 34.5136344), '16 East Drive', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Anthropoides paradisea', point(46.068811, 6.568907), '607 Sachs Court', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Sylvicapra grimma', point(15.0541658, -91.229784), '35 Quincy Court', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Bettongia penicillata', point(45.4514411, 18.6589341), '145 Mallard Crossing', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Sylvilagus floridanus', point(-10.22485, 120.548897), '31 Fallview Crossing', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Lamprotornis chalybaeus', point(58.9919268, 16.2203271), '7 International Drive', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Haematopus ater', point(32.460037, 112.228897), '6 Arrowood Plaza', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Procyon lotor', point(43.4650355, 24.8715019), '07764 New Castle Drive', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Turtur chalcospilos', point(54.026345, -7.297914), '88254 Summer Ridge Street', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Tursiops truncatus', point(11.1054336, 42.3704744), '9 Oakridge Drive', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Eudyptula minor', point(36.85608, 81.660646), '2522 John Wall Parkway', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Bos taurus', point(-2.9083521, 29.8265492), '358 Cottonwood Crossing', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Hippotragus equinus', point(30.9457638, 121.4371451), '6118 Kinsman Crossing', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Snycerus caffer', point(9.9010414, -83.9977527), '2 Eggendart Drive', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Lorythaixoides concolor', point(29.858629, 117.6134553), '471 Di Loreto Lane', false);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Lasiorhinus latifrons', point(-6.7216825, 111.1995479), '828 Arrowood Way', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Cervus duvauceli', point(53.701556, 91.680719), '02 Mayer Point', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Diomedea irrorata', point(53.1986, 23.20779), '73 Crownhardt Drive', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Ictalurus furcatus', point(14.437059, 120.989883), '30686 Kings Circle', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Drymarchon corias couperi', point(53.9096, 37.736), '6397 Tennyson Place', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Erethizon dorsatum', point(14.5699334, 121.0204582), '7762 Jay Circle', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Toxostoma curvirostre', point(35.580996, 116.986503), '225 Golden Leaf Hill', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Felis concolor', point(48.9776332, 34.9908882), '6 Bonner Lane', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Gymnorhina tibicen', point(-2.3286839, -79.4056784), '73408 Warner Point', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Tockus flavirostris', point(45.8585463, 39.6551933), '68 Continental Street', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Ramphastos tucanus', point(-10.8064536, -37.1901616), '2 Shopko Alley', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Phalacrocorax carbo', point(41.6, -93.61), '0106 Mcbride Street', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Streptopelia senegalensis', point(22.9290295, -82.3912892), '0296 Dixon Pass', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Acrobates pygmaeus', point(39.6208162, -8.6563967), '3 Division Avenue', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Phalacrocorax brasilianus', point(51.5320956, 17.9737831), '9 Buena Vista Point', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Plegadis falcinellus', point(32.323256, 105.96282), '1964 Manufacturers Plaza', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Coluber constrictor', point(-7.9675496, 110.3368391), '8019 Farmco Drive', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Crotalus cerastes', point(-26.9165792, -49.0717331), '44788 Heath Trail', true);
INSERT INTO emergency_rooms (name, location, displayable_address, is_open) VALUES ('Orcinus orca', point(45.477613, 124.47553), '72 Meadow Vale Avenue', true);

-- Departments

INSERT INTO departments (name) VALUES ('CT');
INSERT INTO departments (name) VALUES ('Neurosurgery');
INSERT INTO departments (name) VALUES ('Trauma Care');

INSERT INTO departments (name) VALUES ('Stronghold');
INSERT INTO departments (name) VALUES ('Konklab');
INSERT INTO departments (name) VALUES ('Y-find');
INSERT INTO departments (name) VALUES ('Stringtough');
INSERT INTO departments (name) VALUES ('Prodder');
INSERT INTO departments (name) VALUES ('Lotstring');
INSERT INTO departments (name) VALUES ('Bigtax');
INSERT INTO departments (name) VALUES ('Hatity');
INSERT INTO departments (name) VALUES ('Quo Lux');
INSERT INTO departments (name) VALUES ('Job');
INSERT INTO departments (name) VALUES ('Tempsoft');
INSERT INTO departments (name) VALUES ('Regrant');
INSERT INTO departments (name) VALUES ('Sonsing');
INSERT INTO departments (name) VALUES ('Cardify');
INSERT INTO departments (name) VALUES ('Wrapsafe');
INSERT INTO departments (name) VALUES ('Keylex');
INSERT INTO departments (name) VALUES ('Veribet');
INSERT INTO departments (name) VALUES ('Opela');
INSERT INTO departments (name) VALUES ('Biodex');
INSERT INTO departments (name) VALUES ('Stim');
INSERT INTO departments (name) VALUES ('Zontrax');
INSERT INTO departments (name) VALUES ('Asoka');
INSERT INTO departments (name) VALUES ('Subin');
INSERT INTO departments (name) VALUES ('Transcof');
INSERT INTO departments (name) VALUES ('Pannier');
INSERT INTO departments (name) VALUES ('Greenlam');
INSERT INTO departments (name) VALUES ('Home Ing');
INSERT INTO departments (name) VALUES ('Rank');
INSERT INTO departments (name) VALUES ('Andalax');
INSERT INTO departments (name) VALUES ('Vagram');
INSERT INTO departments (name) VALUES ('Fixflex');
INSERT INTO departments (name) VALUES ('Tampflex');
INSERT INTO departments (name) VALUES ('Voltsillam');
INSERT INTO departments (name) VALUES ('Span');
INSERT INTO departments (name) VALUES ('Kanlam');
INSERT INTO departments (name) VALUES ('Namfix');
INSERT INTO departments (name) VALUES ('Alpha');
INSERT INTO departments (name) VALUES ('Zaam-Dox');
INSERT INTO departments (name) VALUES ('Bamity');

-- Many to many
-- each room has 1 to 3 departments
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Ephippiorhynchus mycteria' AND d.name = 'Transcof';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Ephippiorhynchus mycteria' AND d.name = 'Konklab';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Ephippiorhynchus mycteria' AND d.name = 'Lotstring';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Deroptyus accipitrinus' AND d.name = 'Bigtax';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Deroptyus accipitrinus' AND d.name = 'Keylex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Ploceus intermedius' AND d.name = 'Zontrax';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'unavailable' AND d.name = 'Vagram';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'unavailable' AND d.name = 'Tampflex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'unavailable' AND d.name = 'Trauma Care';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Neotoma sp.' AND d.name = 'Stronghold';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Caiman crocodilus' AND d.name = 'Hatity';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Caiman crocodilus' AND d.name = 'Cardify';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Caiman crocodilus' AND d.name = 'Biodex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Axis axis' AND d.name = 'Zaam-Dox';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Anas bahamensis' AND d.name = 'Keylex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Anas bahamensis' AND d.name = 'Opela';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Lophoaetus occipitalis' AND d.name = 'Asoka';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Lophoaetus occipitalis' AND d.name = 'Kanlam';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Lophoaetus occipitalis' AND d.name = 'Biodex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Salvadora hexalepis' AND d.name = 'Sonsing';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Salvadora hexalepis' AND d.name = 'Bamity';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Myiarchus tuberculifer' AND d.name = 'Zaam-Dox';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Haliaeetus leucocephalus' AND d.name = 'Opela';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Haliaeetus leucocephalus' AND d.name = 'Voltsillam';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Haliaeetus leucocephalus' AND d.name = 'Stronghold';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Colaptes campestroides' AND d.name = 'Namfix';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Colaptes campestroides' AND d.name = 'Andalax';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Colaptes campestroides' AND d.name = 'Bamity';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Taurotagus oryx' AND d.name = 'Wrapsafe';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Taurotagus oryx' AND d.name = 'Job';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Taurotagus oryx' AND d.name = 'Zaam-Dox';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Semnopithecus entellus' AND d.name = 'Bamity';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Semnopithecus entellus' AND d.name = 'Konklab';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Semnopithecus entellus' AND d.name = 'Neurosurgery';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Equus hemionus' AND d.name = 'Bamity';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Equus hemionus' AND d.name = 'Alpha';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Equus hemionus' AND d.name = 'Zontrax';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Sciurus vulgaris' AND d.name = 'Quo Lux';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Sciurus vulgaris' AND d.name = 'Hatity';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Phascogale calura' AND d.name = 'Lotstring';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Nyctereutes procyonoides' AND d.name = 'Namfix';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Nyctereutes procyonoides' AND d.name = 'Andalax';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Ceratotherium simum' AND d.name = 'Fixflex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Ceratotherium simum' AND d.name = 'Namfix';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Priodontes maximus' AND d.name = 'Quo Lux';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Limnocorax flavirostra' AND d.name = 'CT';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Limnocorax flavirostra' AND d.name = 'Tempsoft';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Hystrix cristata' AND d.name = 'Neurosurgery';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Hystrix cristata' AND d.name = 'Home Ing';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Castor fiber' AND d.name = 'Stronghold';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Castor fiber' AND d.name = 'Transcof';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Manouria emys' AND d.name = 'Regrant';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Manouria emys' AND d.name = 'Y-find';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Eutamias minimus' AND d.name = 'Greenlam';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Eutamias minimus' AND d.name = 'Trauma Care';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Eutamias minimus' AND d.name = 'Opela';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Cynictis penicillata' AND d.name = 'Neurosurgery';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Cynictis penicillata' AND d.name = 'undefined';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Amazona sp.' AND d.name = 'Tempsoft';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Amazona sp.' AND d.name = 'Opela';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Choloepus hoffmani' AND d.name = 'Stringtough';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Choloepus hoffmani' AND d.name = 'Konklab';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Butorides striatus' AND d.name = 'Wrapsafe';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Butorides striatus' AND d.name = 'Keylex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Zalophus californicus' AND d.name = 'Asoka';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Zalophus californicus' AND d.name = 'Wrapsafe';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Ardea golieth' AND d.name = 'Voltsillam';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Ardea golieth' AND d.name = 'Cardify';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Felis silvestris lybica' AND d.name = 'Fixflex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Felis silvestris lybica' AND d.name = 'Sonsing';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Cracticus nigroagularis' AND d.name = 'Trauma Care';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Cracticus nigroagularis' AND d.name = 'Voltsillam';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Cracticus nigroagularis' AND d.name = 'Tampflex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Leptoptilos crumeniferus' AND d.name = 'Regrant';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Leptoptilos crumeniferus' AND d.name = 'Veribet';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Tachybaptus ruficollis' AND d.name = 'Zaam-Dox';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Columba livia' AND d.name = 'Tampflex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Milvus migrans' AND d.name = 'Fixflex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Milvus migrans' AND d.name = 'Biodex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Eudromia elegans' AND d.name = 'Span';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Eudromia elegans' AND d.name = 'Tampflex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Stercorarius longicausus' AND d.name = 'Trauma Care';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Stercorarius longicausus' AND d.name = 'Rank';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Dusicyon thous' AND d.name = 'Voltsillam';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Dusicyon thous' AND d.name = 'Home Ing';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Trichosurus vulpecula' AND d.name = 'Y-find';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Trichosurus vulpecula' AND d.name = 'Keylex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Ammospermophilus nelsoni' AND d.name = 'Lotstring';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Ammospermophilus nelsoni' AND d.name = 'Regrant';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Alopochen aegyptiacus' AND d.name = 'Cardify';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Alopochen aegyptiacus' AND d.name = 'Zontrax';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Charadrius tricollaris' AND d.name = 'Sonsing';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Arctogalidia trivirgata' AND d.name = 'Voltsillam';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Arctogalidia trivirgata' AND d.name = 'Span';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Zosterops pallidus' AND d.name = 'Trauma Care';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Zosterops pallidus' AND d.name = 'CT';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Felis yagouaroundi' AND d.name = 'Konklab';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Felis yagouaroundi' AND d.name = 'Home Ing';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Bucephala clangula' AND d.name = 'Tempsoft';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Bucephala clangula' AND d.name = 'Alpha';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Bucephala clangula' AND d.name = 'Lotstring';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Pseudalopex gymnocercus' AND d.name = 'Stronghold';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Pseudalopex gymnocercus' AND d.name = 'Span';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Phasianus colchicus' AND d.name = 'Subin';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Phasianus colchicus' AND d.name = 'Veribet';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Morelia spilotes variegata' AND d.name = 'Prodder';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Morelia spilotes variegata' AND d.name = 'Transcof';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Ovibos moschatus' AND d.name = 'Zontrax';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Buteo galapagoensis' AND d.name = 'Greenlam';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Buteo galapagoensis' AND d.name = 'Bigtax';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Canis mesomelas' AND d.name = 'Opela';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Anthropoides paradisea' AND d.name = 'Sonsing';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Sylvicapra grimma' AND d.name = 'Sonsing';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Sylvicapra grimma' AND d.name = 'Regrant';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Bettongia penicillata' AND d.name = 'Y-find';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Bettongia penicillata' AND d.name = 'Konklab';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Sylvilagus floridanus' AND d.name = 'Veribet';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Sylvilagus floridanus' AND d.name = 'Kanlam';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Lamprotornis chalybaeus' AND d.name = 'Greenlam';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Lamprotornis chalybaeus' AND d.name = 'Transcof';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Haematopus ater' AND d.name = 'Greenlam';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Haematopus ater' AND d.name = 'Hatity';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Haematopus ater' AND d.name = 'Opela';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Procyon lotor' AND d.name = 'Subin';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Procyon lotor' AND d.name = 'Keylex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Procyon lotor' AND d.name = 'Opela';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Turtur chalcospilos' AND d.name = 'Pannier';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Turtur chalcospilos' AND d.name = 'Y-find';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Tursiops truncatus' AND d.name = 'Span';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Tursiops truncatus' AND d.name = 'Transcof';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Eudyptula minor' AND d.name = 'Quo Lux';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Eudyptula minor' AND d.name = 'Konklab';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Eudyptula minor' AND d.name = 'Wrapsafe';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Bos taurus' AND d.name = 'Andalax';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Bos taurus' AND d.name = 'Neurosurgery';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Hippotragus equinus' AND d.name = 'Trauma Care';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Hippotragus equinus' AND d.name = 'Voltsillam';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Hippotragus equinus' AND d.name = 'Hatity';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Snycerus caffer' AND d.name = 'Y-find';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Lorythaixoides concolor' AND d.name = 'Konklab';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Lorythaixoides concolor' AND d.name = 'Stringtough';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Lorythaixoides concolor' AND d.name = 'Quo Lux';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Lasiorhinus latifrons' AND d.name = 'Alpha';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Cervus duvauceli' AND d.name = 'Namfix';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Cervus duvauceli' AND d.name = 'Fixflex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Diomedea irrorata' AND d.name = 'Vagram';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Diomedea irrorata' AND d.name = 'Quo Lux';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Ictalurus furcatus' AND d.name = 'Stringtough';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Ictalurus furcatus' AND d.name = 'Prodder';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Drymarchon corias couperi' AND d.name = 'Namfix';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Drymarchon corias couperi' AND d.name = 'Bamity';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Erethizon dorsatum' AND d.name = 'Kanlam';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Toxostoma curvirostre' AND d.name = 'Vagram';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Felis concolor' AND d.name = 'Hatity';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Gymnorhina tibicen' AND d.name = 'Tempsoft';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Gymnorhina tibicen' AND d.name = 'Tampflex';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Gymnorhina tibicen' AND d.name = 'Lotstring';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Tockus flavirostris' AND d.name = 'Bigtax';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Tockus flavirostris' AND d.name = 'Bamity';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Tockus flavirostris' AND d.name = 'Y-find';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Ramphastos tucanus' AND d.name = 'Stronghold';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Ramphastos tucanus' AND d.name = 'Vagram';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Phalacrocorax carbo' AND d.name = 'Sonsing';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Phalacrocorax carbo' AND d.name = 'Home Ing';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Phalacrocorax carbo' AND d.name = 'Alpha';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Streptopelia senegalensis' AND d.name = 'Alpha';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Streptopelia senegalensis' AND d.name = 'Y-find';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Acrobates pygmaeus' AND d.name = 'Stringtough';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Acrobates pygmaeus' AND d.name = 'Job';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Phalacrocorax brasilianus' AND d.name = 'Prodder';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Phalacrocorax brasilianus' AND d.name = 'Neurosurgery';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Plegadis falcinellus' AND d.name = 'Hatity';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Plegadis falcinellus' AND d.name = 'Pannier';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Plegadis falcinellus' AND d.name = 'Andalax';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Coluber constrictor' AND d.name = 'Stringtough';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Coluber constrictor' AND d.name = 'Kanlam';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Crotalus cerastes' AND d.name = 'Bamity';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Crotalus cerastes' AND d.name = 'Span';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Crotalus cerastes' AND d.name = 'Stringtough';
INSERT INTO rooms_have_departments SELECT r.id AS emergency_room_id, d.id AS department_id FROM emergency_rooms AS r, departments AS d WHERE r.name = 'Orcinus orca' AND d.name = 'Biodex';
